const actionTypes = {
  // AUTH
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN: "LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAIL: "RESET_PASSWORD_FAIL",
  // POST
  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_POSTS_DETAIL: "GET_POSTS_DETAIL",
  GET_NEW_POST: "GET_NEW_POST",
  GET_POST_USER: "GET_POST_USER",
  EDIT_POST: "EDIT_POST",
  RESET_DATA: 'RESET_DATA',
  GET_POST_BY_ADMIN: 'GET_POST_BY_ADMIN',
  DATA_POST: 'DATA_POST',
  // APP
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: "GET_PRICES",
  GET_AREAS: "GET_AREAS",
  GET_PROVINCES: "GET_PROVINCES",
  // USER
  GET_USER: "GET_USER",
  ALL_USER: 'ALL_USER',
  EDIT_USER: 'EDIT_USER'
};

export default actionTypes;
