const actionTypes = {
  // AUTH
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN: "LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAIL: "RESET_PASSWORD_FAIL",
  // POST
  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_NEW_POST: "GET_NEW_POST",
  // APP
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: "GET_PRICES",
  GET_AREAS: "GET_AREAS",
  GET_PROVINCES: "GET_PROVINCES",
  // USER
  GET_CURRENT: "GET_CURRENT",
};

export default actionTypes;
